Error fetching data from http://65.108.233.71:8080/v1: HTTPConnectionPool(host='65.108.233.71', port=8080): Max retries exceeded with url: /v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7facec7c2b90>: Failed to establish a new connection: [Errno 111] Connection refused'))
{'http://73.181.115.53:8080/v1': 1792100, 'http://70.15.242.6:8080/v1': 1792100, 'http://65.109.80.179:8080/v1': 1792100, 'http://65.108.230.116:8080/v1': 1792100, 'http://65.108.15.240:8080/v1': 1792102, 'http://51.159.100.217:8080/v1': 1381594, 'http://222.101.31.242:8080/v1': 1792104, 'http://172.104.211.8:8080/v1': 1792106, 'http://158.220.123.33:8080/v1': 1792106, 'http://142.132.217.22:8080/v1': 1792106, 'http://50.29.171.32:8080/v1': 1755416}
Nginx configuration updated!
