Error fetching data from http://94.130.22.86:8080/v1: HTTPConnectionPool(host='94.130.22.86', port=8080): Max retries exceeded with url: /v1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9f56a91ab0>, 'Connection to 94.130.22.86 timed out. (connect timeout=5)'))
Error fetching data from http://136.243.59.175:8080/v1: HTTPConnectionPool(host='136.243.59.175', port=8080): Max retries exceeded with url: /v1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9f56a93040>, 'Connection to 136.243.59.175 timed out. (connect timeout=5)'))
Error fetching data from http://144.76.104.93:8080/v1: HTTPConnectionPool(host='144.76.104.93', port=8080): Max retries exceeded with url: /v1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9f56a93790>, 'Connection to 144.76.104.93 timed out. (connect timeout=5)'))
Error fetching data from http://94.130.22.86:8080/v1: HTTPConnectionPool(host='94.130.22.86', port=8080): Max retries exceeded with url: /v1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9f56a93ee0>, 'Connection to 94.130.22.86 timed out. (connect timeout=5)'))
{'http://70.15.242.6:8080/v1': 26184438, 'http://73.181.115.53:8080/v1': 26184438, 'http://104.248.94.195:8080/v1': 26184526}
Nginx configuration updated!
